### PR TITLE
add counting down while verifying email address

### PR DESCRIPTION
**Pull request by AlaaElattar**
- https://github.com/threefoldtech/threefold_connect/issues/558

https://github.com/user-attachments/assets/dd0a7f6c-0d22-44f3-bffb-846e7180772f

### Tested Scenarios:
- Tried to validate email and counter worked well

### CODE REVIEW

**Comment by zaelgohary** [comment]
Please add tested scenarios and resolve conflicts.

**Review by AhmedHanafy725 — CHANGES_REQUESTED** [review]
the verify button is clickable even if it's disabled while counting down

image

**Comment by AlaaElattar** [comment]
> the verify button is clickable even if it's disabled while counting down
> 
> image

should be fixed

**Review by AhmedHanafy725 — COMMENTED** [review]
it doesn't work for the first time

https://github.com/user-attachments/assets/d248c526-5262-4195-beb6-323a90f69d2a

**Comment by AlaaElattar** [comment]
> it doesn't work for the first time
> 
>  Screenrecorder-2024-11-25-11-59-45-170.mp4

- Fixed 

https://github.com/user-attachments/assets/e9f0d93d-184a-482b-a4ab-9ea2c0ef9d3e

**Review by AhmedHanafy725 — CHANGES_REQUESTED** [review]
it forgets me if l left the screen

https://github.com/user-attachments/assets/92cb2427-ac6d-479a-9fb4-16e1a7df0300

**Review by AhmedHanafy725 — APPROVED** [review]

**Pull request merged**
